version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git 
      - app-config
            steps:
              - run:
                  name: "Setup config vars"
                  command: heroku config:set YELP_CLIENT_ID=$YELP_CLIENT_ID YELP_API_KEY=$YELP_API_KEY YELP_URL=$YELP_URL
