version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
          post-steps:
            - run: heroku config:set YELP_CLIENT_ID=$YELP_CLIENT_ID
            - run: heroku config:set YELP_API_KEY=$YELP_API_KEY
            - run: heroku config:set YELP_URL=$YELP_URL
